version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    env_file:
      - .env  # 현재 디렉토리에 있으므로 상대경로 아님

  model-api:
    build:
      context: ./model-api
      dockerfile: Dockerfile
    container_name: model-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  model-worker:
    build:
      context: ./model-worker
      dockerfile: Dockerfile
    container_name: model-worker
    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  model_cache:
