services:
  auth:
    build:
      context: ./k-animator-project
      dockerfile: ./auth/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./k-animator-project/auth/.env
    volumes:
      - ./k-animator-project/auth:/app/auth
      - ./k-animator-project/shared:/app/shared
  
  frontend:
    build:
      context: ./front_test
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./front_test/html:/usr/share/nginx/html
      - ./front_test/css:/usr/share/nginx/html/css
      - ./front_test/js:/usr/share/nginx/html/js
      - ./front_test/images:/usr/share/nginx/html/images