apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-sa
      containers:
        - name: auth
          image: ghcr.io/woosung142/k-animator/auth:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: app-secrets
      imagePullSecrets:
        - name: ghcr-secret
