apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: ghcr.io/woosung142/k-animator/model-api:main
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: TRANSFORMERS_CACHE
              value: /models
          volumeMounts:
            - mountPath: /models
              name: model-cache
      volumes:
        - name: model-cache
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr-secret
