apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-worker
  template:
    metadata:
      labels:
        app: model-worker
    spec:
      serviceAccountName: model-worker-sa
      containers:
        - name: model-worker
          image: ghcr.io/woosung142/k-animator/model-worker:main
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: ghcr-secret