apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alert
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: high-cpu-usage
    rules:
    - alert: HighCpuUsage-test4
      #알림 조건 정의
      expr: 100 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) > 1 #쿼리문 수정
      for: 1m
      labels:
        severity: warning
      #알림 메시지 내용
      annotations:
        summary: "High CPU usage on instance {{ $labels.instance }}"
        description: "The CPU usage on instance {{ $labels.instance }} has exceeded the threshold. Current usage: {{ $value | printf `%.2f` }}%"