apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress-for-apim
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
              
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80

      - path: /api/model
        pathType: Prefix
        backend:
          service:
            name: modelapi-service
            port:
              number: 80

      - path: /api/utils
        pathType: Prefix
        backend:
          service:
            name: utils-service
            port:
              number: 80

      - path: /api/gpt
        pathType: Prefix
        backend:
          service:
            name: gptapi-service
            port:
              number: 80

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

