apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress-for-apim # APIM 연동용임을 명시
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # TLS/SSL 및 도메인 관련 어노테이션은 모두 APIM이 담당하므로 제거합니다.
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  # host를 명시하지 않아 Ingress Controller의 IP로 들어오는 모든 요청을 처리합니다.
  - http:
      paths:
      # --- [수정] Auth & Users API 라우팅 ---
      # /api/auth/* 및 /api/users/* 요청은 모두 auth-service로 전달됩니다.
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80

      # --- [수정] Model API 라우팅 ---
      # /api/model/* 요청은 model-api 서비스로 전달됩니다.
      - path: /api/model
        pathType: Prefix
        backend:
          service:
            name: model-api-service
            port:
              number: 80

      # --- [수정] Util API 라우팅 ---
      # /api/utils/* 요청은 backend-service (또는 util-service)로 전달됩니다.
      - path: /api/utils
        pathType: Prefix
        backend:
          service:
            name: util-service # Terraform의 util_api에 해당
            port:
              number: 80
              
      # --- 프론트엔드 라우팅 규칙 (가장 마지막에 위치) ---
      # 위 경로에 해당하지 않는 모든 요청은 프론트엔드로 전달됩니다.
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

