version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
      - GENERIC_TIMEZONE=Asia/Seoul
      - N8N_SECURE_COOKIE=false #HTTPS 거부용
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
