apiVersion: argroj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/woosung142/K-animator'
    targetRevision: main
    path: k8s/infrastructure/ingress-nginx
    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true