apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k-animator-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/woosung142/K-animator
      revision: HEAD
      branches:
      - main
  - git:
      repoURL: https://github.com/woosung142/K-animator
      revision: HEAD
      branches:
      - 'feature/*'
      
  template:
    metadata:
      name: 'k-animator-{{branchNormalized}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/woosung142/K-animator'
        path: k8s/manifests
        targetRevision: '{{branch}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{#contains "feature" branch}}k-animator-{{branchNormalized}}{{/contains}}{{^contains "feature" branch}}default{{/contains}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true