apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ajh9789/k8s-deploy'
    targetRevision: feature/app-of-apps-refactor    
    path: k8s/manifests                               
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true