piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/woosung142/K-animator'
    targetRevision: main    
    path: k8s/manifests                               
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true