apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-deploy.fullname" . }}-model-api
  labels:
    {{- include "k8s-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-api
spec:
  replicas: {{ .Values.modelApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-deploy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: model-api
  template:
    metadata:
      labels:
        {{- include "k8s-deploy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: model-api
    spec:
      containers:
        - name: model-api
          image: "{{ .Values.modelApi.image.repository }}:{{ .Values.modelApi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.modelApi.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.modelApi.service.port }}
          env:
            - name: TRANSFORMERS_CACHE
              value: {{ .Values.modelApi.env.TRANSFORMERS_CACHE }}
          volumeMounts:
            - mountPath: {{ .Values.modelApi.env.TRANSFORMERS_CACHE }}
              name: model-cache
      volumes:
        - name: model-cache
          emptyDir: {}
