apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-storage-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=0
    - gid=0
    - mfsymlinks
    - actimeo=30
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: "k-animator_kanimatormodelsa_kanimator-sd-models"
    volumeAttributes:
      shareName: "kanimator-sd-models" 
    nodeStageSecretRef:
      name: azure-storage-secret