version: '3.8'

services:
  # 서비스 이름 (원하는 대로 지정 가능)
  web-server:
    # 현재 폴더의 Dockerfile을 사용하여 이미지 빌드
    build: .
    ports:
      # 내 컴퓨터의 3000번 포트와 컨테이너의 3000번 포트 연결
      - "3000:3000"
    volumes:
      # [핵심!] 내 컴퓨터의 현재 폴더(.)를 컨테이너의 /usr/src/app 폴더에 연결합니다.
      # 이제 내 컴퓨터에서 코드를 수정하면 즉시 컨테이너 내부에도 반영됩니다.
      - .:/usr/src/app
      # 컨테이너 안의 node_modules는 동기화하지 않도록 예외 처리합니다.
      # (내 컴퓨터와 컨테이너의 운영체제가 달라 생길 수 있는 충돌 방지)
      - /usr/src/app/node_modules
    env_file:
      - .env