name: Build, Push and Update Manifests

on:
  push:
    branches: [main, develop]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      service_changes: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Detect changed services
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            frontend:
              - 'k-animator-project/frontend/**'
            auth:
              - 'k-animator-project/auth/**'
            model-api:
              - 'k-animator-project/model_api/**'
            model-worker:
              - 'k-animator-project/model_worker/**'
            util:
              - 'k-animator-project/util/**'

  build-and-push:
    needs: changes
    if: ${{ needs.changes.outputs.service_changes != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.service_changes) }}
        
    outputs:
      build_data: ${{ steps.prepare_output.outputs.data }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to GHCR
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WOOSUNG142 }}
      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/k-animator/${{ matrix.service }}
          tags: |
            type=ref,event=branch,prefix={{branch}}-,suffix=-{{sha}}

      - name: Set Docker build context
        id: set-context
        run: |
          SERVICE_NAME="${{ matrix.service }}"
          SERVICE_PATH=""
          case "$SERVICE_NAME" in
            "frontend")     SERVICE_PATH="k-animator-project/frontend" ;;
            "auth")         SERVICE_PATH="k-animator-project/auth" ;;
            "model-api")    SERVICE_PATH="k-animator-project/model_api" ;;
            "model-worker") SERVICE_PATH="k-animator-project/model_worker" ;;
            "util")         SERVICE_PATH="k-animator-project/util" ;;
            *)
              echo "::error::Unknown service name: $SERVICE_NAME"
              exit 1
              ;;
          esac
          echo "path=${SERVICE_PATH}" >> $GITHUB_OUTPUT
      - name: Build and Push image to GHCR
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./k-animator-project
          file: ${{ steps.set-context.outputs.path }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Prepare build data output
        id: prepare_output
        run: |
          JSON_STRING=$(jq -n --arg service "${{ matrix.service }}" --arg tag "${{ steps.meta.outputs.tags }}" '{service: $service, tag: $tag}')
          {
            echo "data<<EOF"
            echo "$JSON_STRING"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  update-manifests:
    needs: [changes, build-and-push]
    if: ${{ needs.changes.outputs.service_changes != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.WOOSUNG142 }}
      - name: Update Kustomize Manifest
        env:
          BUILD_DATA_ARRAY: ${{ toJSON(needs.build-and-push.outputs.build_data) }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            KUSTOMIZE_PATH="k8s/manifests/overlays/production/kustomization.yaml"
          else
            KUSTOMIZE_PATH="k8s/manifests/overlays/development/kustomization.yaml"
          fi

          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq

          echo "$BUILD_DATA_ARRAY" | jq -r '.[]' | while IFS= read -r build_data_json; do
            SERVICE=$(echo "$build_data_json" | jq -r '.service')
            IMAGE_FULL_TAG=$(echo "$build_data_json" | jq -r '.tag')
            IMAGE_TAG=$(echo "$IMAGE_FULL_TAG" | cut -d ':' -f 2)
            echo "Updating image for service: ${SERVICE} with tag: ${IMAGE_TAG}"
            yq e '(.images[] | select(.name | test("ghcr.io/${{ github.repository_owner }}/k-animator/'"$SERVICE"'")) | .newTag) = strenv(IMAGE_TAG)' -i ${KUSTOMIZE_PATH}
          done

          if ! git diff --quiet ${KUSTOMIZE_PATH}; then
            git add ${KUSTOMIZE_PATH}
            git commit -m "ci: Update image tags for changed services on ${{ github.ref_name }}"
            git push
          else
            echo "No changes to commit."
          fi
